name: PHP Composer

on:
  push:
    tags:
      - 'ver.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Prepare release package
      run: |
        mkdir -p topt
        shopt -s extglob
        cp -R !(topt) topt/
        rm -rf topt/tests
        rm -rf topt/.git
        rm -rf topt/.github
        cd topt
        zip -r ../topt.zip .

    - name: Get release upload URL
      id: get_release
      uses: actions/github-script@v6
      with:
        script: |
          const { data: release } = await github.rest.repos.getReleaseByTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: context.ref.substring(10)
          });
          core.setOutput('upload_url', release.upload_url);

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./topt.zip
        asset_name: topt.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        COMPOSER_PROCESS_TIMEOUT: 0
        COMPOSER_NO_INTERACTION: 1
        COMPOSER_NO_AUDIT: 1
